apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-fn4
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: '10'
        autoscaling.knative.dev/min-scale: '0'
        autoscaling.knative.dev/scale-to-zero-grace-period: 10s
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: 0s
        autoscaling.knative.dev/stable-window: 30s
        autoscaling.knative.dev/target: '82'
        autoscaling.knative.dev/target-utilization-percentage: '100'
    spec:
      containers:
      - image: boostedlee/knative-fn4:latest
        ports:
        - containerPort: 8080
